# Generated by Django 5.0.3 on 2024-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='project_usermodel',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
